[tool.poetry]
name = "RoboNerva"
version = "1.0.0"
description = "Community manager bot for the Nerva (XNV) cryptocurrency."
license = "GPL-3.0"
authors = ["Sayan Bhattacharyya <sn1f3rt@outlook.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.8"
discord-ext-menus = {git = "https://github.com/Rapptz/discord-ext-menus"}
discord-ext-menus-views = {git = "https://github.com/FumeStop/discord-ext-menus-views"}
discord-py = {extras = ["speed"], version = "^2.4.0"}
dnspython = "^2.6.1"
motor = "^3.6.0"
python-telegram-bot = "^21.6"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
black = "^24.8.0"
isort = "^5.13.2"

[tool.poetry.group.scripts]
optional = true

[tool.poetry.group.scripts.dependencies]
aiocsv = "^1.3.2"
aiofiles = "^24.1.0"
python-dateutil = "^2.9.0.post0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 85
target-version = ["py311"]

[tool.isort]
profile = "black"
known_future_library = ["__future__"]
known_typing = ["typing"]
sections = ["FUTURE", "TYPING", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
default_section = "THIRDPARTY"
line_length = 85
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
length_sort = true
