name: Run isort

on: [ push, pull_request ]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: isort/isort-action@v1
                with:
                    configuration: "--settings-path pyproject.toml --check-only --diff"
